name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI Process
    runs-on: ubuntu-latest
    env:
      GOLANG_VERSION: '1.20'
      CGO_ENABLED: 0
      GOLANGCI_LINT_VERSION: v1.52.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum
      - name: Build Go Code
        run: |
          make build
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Run Go Tests
        run: |
          make test
      - name: Build Docker Image
        run: |
          make docker/build
