name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-process:
    name: CI Process
    runs-on: ubuntu-latest
    env:
      GOLANG_VERSION: 1.20
      CGO_ENABLED: 0
      GOLANGCI_LINT_VERSION: v1.52.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download all Go modules
        run: |
          go mod download
      - name: Check for tidyness of go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code -- .
      - name: Verify Go modules
        run: |
          go mod verify
      - name: Compile all packages
        run: |
          go build -v $(go list ./... | grep -v /vendor/ | tr '\n' ' ')
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - name: Run Go Tests
        run: |
          go test -short -race -coverprofile coverage.txt -covermode atomic $(go list ./... | grep -v /vendor/ | tr '\n' ' ')
          go tool cover -func=coverage.txt
      - name: Upload code coverage information to codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: coverage.txt
