name: Matrix
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cross:
    name: Go ${{ matrix.go-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0
    strategy:
      matrix:
        go-version: [ '1.20', '1.x' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build Go Code
        run: |
          go build -a --trimpath --installsuffix cgo --ldflags="-s -w" -o diade ./cmd/diade-api/main.go
      - name: Run Go Tests
        run: |
          go test -v -cover ./...
